# Generated by Django 4.1.5 on 2023-01-26 17:02

# Este archivo contiene la tabla

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla_uno_project',
            # Campos
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
    
    # Ejecutar para migrar (esto nos permite cambiar la estructura
    # de la base de datos) a la base de datos python manage.py migrate myapp
