# Generated by Django 4.1.5 on 2023-01-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # esta dependencia se genero por la relacion foranea de esta tabla con la de 001_initial.py

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_tareas_del_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tabla_uno_project')),
            ],
        ),
    ]
